### ISSUE TITLE
摸鱼日历和早报自动推送报错

### ISSUE THREAD

**Issue by WillyerQ** [AiYuuki/Yuuki-plugin-mini#4]
![Screenshot_2023-03-08-08-18-32-257_com microsoft rdc androidx](https://user-images.githubusercontent.com/126785476/223586521-69fcf76d-edb4-44a3-b931-89b50837146a.jpg)
设定好自动推送之后，推送报错，但是手动推送没问题

**Comment by AiYuuki** [comment]
用的 Miao-Yunzai 吗，我还没测试，有空我看看

**Comment by WillyerQ** [comment]
好的，谢谢

**Comment by funnyrus** [comment]
早报的第60行判断，e instanceof Group改成e.group_id可以暂时解决这个问题（测试用的喵喵的Yunzai-Bot，miao-yunzai没测试）

**Comment by WillyerQ** [comment]
好了，可以推送了，谢谢大佬
![P2$HN(FSA 96AMA7~`SDB2C](https://user-images.githubusercontent.com/126785476/224471458-26c5c1f5-b1c2-47df-b547-56afb39675c0.png)

**Comment by WillyerQ** [comment]
但是会重复发送

**Comment by funnyrus** [comment]
> 

好像还有点问题，群里手动发布会误判改成e.group_id && !e.user_id可能会解决，不需要手动可以不改。重复发布是每次修改都会生成一次定时，改几次就会发几遍，重启yunzai就可以了

**Comment by AiYuuki** [comment]
> > 
> 
> 好像还有点问题，群里手动发布会误判改成e.group_id && !e.user_id可能会解决，不需要手动可以不改。重复发布是每次修改都会生成一次定时，改几次就会发几遍，重启yunzai就可以了

刚刚想到可以通过可选参数判断是不是自动推送，不走 OICQ / ICQQ 的 API 判断，或许会更可靠。
```
async function pushNews(e, isAuto = 0) {
    ...
    if (isAuto) {
      e.sendMsg(segment.image(res))
    } else {
      e.reply(segment.image(res))
    }
}
```
