### ISSUE TITLE
日报推送生成不了图片报错如下

### ISSUE THREAD

**Issue by binwine** [AiYuuki/Yuuki-plugin-mini#6]
图片1失败, reason: Client network socket disconnected before secure TLS connection was established

**Comment by AiYuuki** [comment]
未复现，这个报错应该是服务器网络环境问题

还请提供一下服务器网络环境、Yunzai 版本

**Comment by binwine** [comment]
服务器网络环境指的是什么 Yunzai版本是喵佬的3.0，我刚才换掉了日报里面的import { segment } from 'icqq'

oicq->icqq 重新推送 可以了

**Comment by AiYuuki** [comment]
> 服务器网络环境指的是什么 Yunzai版本是喵佬的3.0，我刚才换掉了日报里面的import { segment } from 'icqq'
> 
> oicq->icqq 重新推送 可以了

哦哦，明白了
