### ISSUE TITLE
摸鱼日历404

### ISSUE THREAD

**Issue by lava081** [AiYuuki/Yuuki-plugin-mini#9]
![20230709_111505_189_edit_761050550827620-01](https://github.com/AiYuuki/Yuuki-plugin-mini/assets/69086800/fd16d0a4-32ef-4428-9eae-7c4645080e48)

**Comment by lava081** [comment]
从网上找了个api
https://api.emoao.com/api/moyu
![9c97e56ffbcf45f6af580b8728c4be89](https://github.com/AiYuuki/Yuuki-plugin-mini/assets/69086800/bd99ad8e-48ab-4284-b781-c92189544416)

**Comment by AiYuuki** [comment]
感谢提供，目前现有的 api 已恢复正常，暂时不做调整
之后如出现类似问题再更换

**Comment by LinBoyan** [comment]
感谢回复，现已能顺利访问现有API

**Comment by lava081** [comment]
感谢回复，现已能顺利访问现有API
